services:
  # TikTok MCP Server
  tiktok-mcp:
    image: node:18-alpine
    container_name: tiktok-mcp
    profiles:
      - tiktok
    ports:
      - "3300:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TIKTOK_API_KEY=${TIKTOK_API_KEY}
      - TIKTOK_API_SECRET=${TIKTOK_API_SECRET}
      - TIKTOK_ACCESS_TOKEN=${TIKTOK_ACCESS_TOKEN}
    volumes:
      - ./data/mcp-servers/tiktok:/app/data
      - ./data/mcp-servers/tiktok/node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "npm install -g @seym0n/tiktok-mcp &&
             tiktok-mcp"
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # YouTube MCP Server
  youtube-mcp:
    image: node:18-alpine
    container_name: youtube-mcp
    profiles:
      - youtube
    ports:
      - "3301:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - YOUTUBE_REFRESH_TOKEN=${YOUTUBE_REFRESH_TOKEN}
    volumes:
      - ./data/mcp-servers/youtube:/app/data
      - ./data/mcp-servers/youtube/node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "npm install -g @zubeidhendricks/youtube-mcp-server &&
             youtube-mcp-server"
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Twitter/X MCP Server
  twitter-mcp:
    image: node:18-alpine
    container_name: twitter-mcp
    profiles:
      - twitter
    ports:
      - "3302:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
    volumes:
      - ./data/mcp-servers/twitter:/app/data
      - ./data/mcp-servers/twitter/node_modules:/app/node_modules
    working_dir: /app
    command: >
      sh -c "npm install -g @mbelinky/x-mcp-server &&
             x-mcp-server"
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # n8n MCP Server
  n8n-mcp:
    image: ghcr.io/czlonkowski/n8n-mcp:latest
    container_name: n8n-mcp
    profiles:
      - n8n-mcp
    ports:
      - "3303:5678"
    environment:
      - MCP_MODE=http
      - N8N_API_URL=${N8N_API_URL}
      - N8N_API_KEY=${N8N_API_KEY}
    volumes:
      - ./data/mcp-servers/n8n-mcp:/app/data
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MCP Dashboard/Status Page
  mcp-dashboard:
    image: nginx:alpine
    container_name: mcp-dashboard
    profiles:
      - dashboard
    ports:
      - "3304:80"
    volumes:
      - ./data/mcp-servers/dashboard:/usr/share/nginx/html
      - ./data/mcp-servers/dashboard/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mcp-network
    restart: unless-stopped
    depends_on:
      - tiktok-mcp
      - youtube-mcp
      - twitter-mcp
      - n8n-mcp

networks:
  mcp-network:
    driver: bridge
    name: mcp-network
