---
- name: Ensure Docker and containers are running
  hosts: local
  become: true

  pre_tasks:
    - name: Ensure required apt packages are installed
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Ensure required Python packages are installed
      ansible.builtin.pip:
        name:
          - "docker<7.0.0"
          - docker-compose

  tasks:
    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started

    - name: Start all containers from docker-compose
      community.docker.docker_compose:
        project_src: "{{ playbook_dir }}"
        state: present
